
let items_menus=[
  {
    id: '01',
    item_img : 'assest/refreshment.png',
    name : 'Refreshment',
    text: 'Green Tea is Big Happines of morning',
    company :'jss',
    original_price: 1045,
    current_price: 606,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    price: 'Rs:250',
    btn: 'Order Now',
  },
  {
    id: '02',
    item_img : 'assest/hot-beverages.png',
    name : 'hot-beverages',
    text: 'Hot-beverages is Big Happines of morning',
    company :'jss',
    original_price: 900,
    current_price: 560,
    discount_percentage: 37.77,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    price: 'Rs:350',
    btn: 'Order Now',
  },
  {
    id: '03',
    item_img : 'assest/cold-beverages.png',
    name : 'Cold-beverage',
    text: 'Cold-beverages is Big Happines of morning',
    company :'jss',
    original_price: 890,
    current_price: 530,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    price: 'Rs:400',
    btn: 'Order Now',
  },
  {
    id: '04',
    item_img : 'assest/expresso.png',
    name : 'Espresso',
    text: 'Green Tea is Big Happines of morning',
    company :'jss',
    original_price: 1500,
    current_price: 900,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    price: 'Rs:550',
    btn: 'Order Now',
  },
  {
    id: '05',
    item_img : 'assest/latte.png',
    name : 'Latte',
    text: 'Green Tea is Big Happines of morning',
    company :'jss',
    original_price: 1045,
    current_price: 606,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    price: 'Rs:650',
    btn: 'Order Now',
  },
  {
    id: '07',
    item_img : 'assest/cappucinno.png',
    name : 'Cappuccino',
    text: 'Cappuccino is Big Happines of morning',
    company :'jss',
    original_price: 1045,
    current_price: 606,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    price: 'Rs:650',
    btn: 'Order Now',
  },
  {
    id: '08',
    item_img : 'assest/desserts.png',
    name : 'Deseret',
    text: 'Deserest  is fruit ful for our health',
    company :'jss',
    original_price: 1150,
    current_price: 950,
    discount_percentage: 17.39,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    price: 'Rs:850',
    btn: 'Order Now',
  },
  {
    id: '09',
    item_img : 'assest/greentea.PNG',
    name : 'Green Tea',
    text: 'Green Tea is Big Happines of morning',
    company :'jss',
    original_price: 1100,
    current_price: 890,
    discount_percentage: 19,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    price: 'Rs:650',
    btn: 'Order Now',
  },
];
